name: Release
on:
  release:
    types:
      - created
jobs:
  release_binary:
    runs-on: [self-hosted, linux]
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Update apt
        run: sudo apt-get -y update
      - name: Install pkg-config
        run: sudo apt-get install -y pkg-config
      - name: Install libssl-dev
        run: sudo apt-get install -y libssl-dev
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Install cargo-edit
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-edit
      - uses: Swatinem/rust-cache@v1
      - name: Set crate version
        uses: actions-rs/cargo@v1
        with:
          command: set-version
          args: ${{ github.ref_name }}
      - name: Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --allow-dirty
